import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import dotenv from 'dotenv';

dotenv.config();

const environmentFilePath = resolve('src/environments/environment.ts');
const isProduction = process.argv.includes('--production');

const requiredVariables = ['SUPABASE_URL', 'SUPABASE_ANON_KEY'];
const missingVariables = requiredVariables.filter((key) => !process.env[key]);

if (missingVariables.length > 0) {
  throw new Error(`Missing environment variables: ${missingVariables.join(', ')}`);
}

const environmentFileContent = `/**
 * Contains generated environment settings.
 * This file is generated by set-env.mjs.
 */
export const environment = {
  production: ${isProduction},
  supabaseUrl: ${JSON.stringify(process.env.SUPABASE_URL)},
  supabaseAnonKey: ${JSON.stringify(process.env.SUPABASE_ANON_KEY)},
};
`;

mkdirSync(dirname(environmentFilePath), { recursive: true });
writeFileSync(environmentFilePath, environmentFileContent);
